# Generated by Django 4.1.3 on 2023-02-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsblog', '0003_contact_delete_tripcalculator'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='status',
            field=models.IntegerField(choices=[(0, 'Draft'), (1, 'Published')], default=0),
        ),
    ]
